In [6]:
import numpy as np

def chessboard_with_numpy(n):
    # Створення матриці розміром n × n, заповненої нулями
    board = np.zeros((n, n), dtype=int)
    
    # Заповнення шахового порядку з використанням слайсінгу
    board[::2, ::2] = 1
    board[1::2, 1::2] = 1
    
    return board

# Введення числа n
n = int(input("Введіть розмірність матриці n × n: "))
chessboard = chessboard_with_numpy(n)
print(chessboard)

Введіть розмірність матриці n × n:  10


[[1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]]


In [7]:
def chessboard_with_loops(n):
    board = []  # Початково пуста матриця
    for i in range(n):
        row = []  # Початково пустий рядок
        for j in range(n):
            # Заповнення шахового порядку
            if (i + j) % 2 == 0:
                row.append(1)
            else:
                row.append(0)
        board.append(row)
    return board

# Введення числа n
n = int(input("Введіть розмірність матриці n × n: "))
chessboard = chessboard_with_loops(n)
for row in chessboard:
    print(row)

Введіть розмірність матриці n × n:  10


[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]


In [3]:
import numpy as np

def generate_array_with_numpy(n, m):
    # Створення матриці розміром n × m
    array = np.zeros((n, m), dtype=int)
    
    # Заповнення першого рядка числами від 0 до m-1
    array[0] = np.arange(m)
    
    return array

# Введення чисел n і m
n = int(input("Введіть кількість рядків (n): "))
m = int(input("Введіть кількість стовпців (m): "))
result_array = generate_array_with_numpy(n, m)
print(result_array)

Введіть кількість рядків (n):  10
Введіть кількість стовпців (m):  10


[[0 1 2 3 4 5 6 7 8 9]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [10]:
def generate_array_with_loops(n, m):
    # Створення порожньої матриці розміром n × m
    array = []
    
    # Заповнення першого рядка числами від 0 до m-1
    first_row = list(range(m))
    array.append(first_row)
    
    # Додавання рядків, які містять лише нулі
    for _ in range(1, n):
        row = [0] * m
        array.append(row)
    
    return array

# Введення чисел n і m
n = int(input("Введіть кількість рядків (n): "))
m = int(input("Введіть кількість стовпців (m): "))
result_array = generate_array_with_loops(n, m)
for row in result_array:
    print(row)

Введіть кількість рядків (n):  10
Введіть кількість стовпців (m):  10


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [11]:
import numpy as np

def generate_array_with_numpy(n):
    # Створення матриці розміром n × n
    array = np.zeros((n, n), dtype=int)
    
    # Заповнення рядків з парними індексами 1
    array[::2] = 1
    
    return array

# Введення числа n
n = int(input("Введіть розмірність матриці n × n: "))
result_array = generate_array_with_numpy(n)
print(result_array)

Введіть розмірність матриці n × n:  10


[[1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]]


In [12]:
def generate_array_with_loops(n):
    # Створення порожньої матриці розміром n × n
    array = []
    
    # Заповнення рядків з парними індексами 1
    for i in range(n):
        if i % 2 == 0:
            row = [1] * n
        else:
            row = [0] * n
        array.append(row)
    
    return array

# Введення числа n
n = int(input("Введіть розмірність матриці n × n: "))
result_array = generate_array_with_loops(n)
for row in result_array:
    print(row)

Введіть розмірність матриці n × n:  10


[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [13]:
import numpy as np

def count_elements_with_numpy(array):
    zero_count = np.count_nonzero(array == 0)
    non_zero_count = np.count_nonzero(array != 0)
    return zero_count, non_zero_count

# Введення масиву з клавіатури
array = np.array(list(map(int, input("Введіть елементи масиву через пробіл: ").split())))

zero_count, non_zero_count = count_elements_with_numpy(array)
print("Кількість нульових елементів:", zero_count)
print("Кількість ненульових елементів:", non_zero_count)

Введіть елементи масиву через пробіл:  0 0 0 0 1


Кількість нульових елементів: 4
Кількість ненульових елементів: 1


In [14]:
def count_elements_with_loops(array):
    zero_count = sum(1 for element in array if element == 0)
    non_zero_count = sum(1 for element in array if element != 0)
    return zero_count, non_zero_count

# Введення масиву з клавіатури
array = list(map(int, input("Введіть елементи масиву через пробіл: ").split()))

zero_count, non_zero_count = count_elements_with_loops(array)
print("Кількість нульових елементів:", zero_count)
print("Кількість ненульових елементів:", non_zero_count)

Введіть елементи масиву через пробіл:  1 1 1 0 2 3 45


Кількість нульових елементів: 1
Кількість ненульових елементів: 6


In [17]:
import numpy as np

def create_array_with_numpy(n):
    array = np.arange(n, -1, -1)
    return array

# Введення числа n
n = int(input("Введіть число n: "))
result_array = create_array_with_numpy(n)
print("Масив:", result_array)

Введіть число n:  22


Масив: [22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [15]:
def create_array_with_loops(n):
    array = [i for i in range(n, -1, -1)]
    return array

# Введення числа n
n = int(input("Введіть число n: "))
result_array = create_array_with_loops(n)
print("Масив:", result_array)

Введіть число n:  15


Масив: [15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [16]:
import numpy as np

def create_frame_with_numpy(n):
    array = np.zeros((n, n), dtype=int)  # Створення масиву розміром n x n заповненого нулями
    array[1:-1, 1:-1] = 1  # Заповнення центральної частини масиву одиницями
    return array

# Введення числа n
n = int(input("Введіть розмірність масиву n x n: "))
result_array = create_frame_with_numpy(n)
print("Масив з рамкою з нулів та центром з одиниць:")
print(result_array)

Введіть розмірність масиву n x n:  22


Масив з рамкою з нулів та центром з одиниць:
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1

In [18]:
def create_frame_with_loops(n):
    array = [[0] * n for _ in range(n)]  # Створення масиву розміром n x n заповненого нулями
    
    # Заповнення центральної частини масиву одиницями
    for i in range(1, n - 1):
        for j in range(1, n - 1):
            array[i][j] = 1
            
    return array

# Введення числа n
n = int(input("Введіть розмірність масиву n x n: "))
result_array = create_frame_with_loops(n)
print("Масив з рамкою з нулів та центром з одиниць:")
for row in result_array:
    print(row)

Введіть розмірність масиву n x n:  5


Масив з рамкою з нулів та центром з одиниць:
[0, 0, 0, 0, 0]
[0, 1, 1, 1, 0]
[0, 1, 1, 1, 0]
[0, 1, 1, 1, 0]
[0, 0, 0, 0, 0]


In [19]:
# Створення рядків з нулями та одиницями
even_row = [0, 1] * 4
odd_row = [1, 0] * 4

# Повторення рядків, щоб створити шахматну дошку
board = [even_row if i % 2 == 0 else odd_row for i in range(8)]

for row in board:
    print(row)

[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]


In [20]:
even_row = [0, 1] * 4
odd_row = [1, 0] * 4

# Формування шахматної дошки
board = []
for i in range(8):
    if i % 2 == 0:
        board.append(even_row)
    else:
        board.append(odd_row)

# Виведення шахматної дошки
for row in board:
    print(row)

[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]


In [21]:
import numpy as np

def fill_matrix_with_numpy(n):
    # Створення порожньої матриці розміром n × n
    matrix = np.zeros((n, n), dtype=int)
    
    # Заповнення парних стовпчиків одиницями
    matrix[:, ::2] = 1
    
    return matrix

# Введення числа n
n = int(input("Введіть розмірність матриці n × n: "))
result_matrix = fill_matrix_with_numpy(n)
print("Матриця з заповненими парними стовпчиками одиницями:")
print(result_matrix)

Введіть розмірність матриці n × n:  10


Матриця з заповненими парними стовпчиками одиницями:
[[1 0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1 0]]


In [22]:
def fill_matrix_with_loops(n):
    # Створення порожньої матриці розміром n × n
    matrix = [[0] * n for _ in range(n)]
    
    # Заповнення парних стовпчиків одиницями
    for i in range(n):
        for j in range(n):
            if j % 2 == 0:
                matrix[i][j] = 1
    
    return matrix

# Введення числа n
n = int(input("Введіть розмірність матриці n × n: "))
result_matrix = fill_matrix_with_loops(n)
print("Матриця з заповненими парними стовпчиками одиницями:")
for row in result_matrix:
    print(row)

Введіть розмірність матриці n × n:  10


Матриця з заповненими парними стовпчиками одиницями:
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]


In [23]:
import numpy as np

def generate_vector_with_numpy(n):
    # Генерування вектора із n елементів на інтервалі (0,1)
    vector = np.linspace(0, 1, num=n, endpoint=False)
    return vector.round(3)

# Введення числа n
n = int(input("Введіть кількість елементів у векторі: "))
result_vector = generate_vector_with_numpy(n)
print("Вектор із {} елементів, рівномірно розміщених на інтервалі (0,1):".format(n))
print(result_vector)

Введіть кількість елементів у векторі:  5


Вектор із 5 елементів, рівномірно розміщених на інтервалі (0,1):
[0.  0.2 0.4 0.6 0.8]


In [24]:
def generate_vector_without_numpy(n):
    # Обчислення кроку між елементами
    step = 1 / n
    
    # Генерування вектора із n елементів на інтервалі (0,1)
    vector = [round(i * step, 3) for i in range(n)]
    return vector

# Введення числа n
n = int(input("Введіть кількість елементів у векторі: "))
result_vector = generate_vector_without_numpy(n)
print("Вектор із {} елементів, рівномірно розміщених на інтервалі (0,1):".format(n))
print(result_vector)

Введіть кількість елементів у векторі:  5


Вектор із 5 елементів, рівномірно розміщених на інтервалі (0,1):
[0.0, 0.2, 0.4, 0.6, 0.8]


In [25]:
import numpy as np

# Коефіцієнти системи рівнянь (ліва частина)
coefficients = np.array([[0, 1, -3, 4],
                         [1, 0, -2, 3],
                         [3, 2, 0, -5],
                         [4, 3, -5, 0]], dtype=float)

# Вільні члени системи рівнянь (права частина)
constants = np.array([-5, -4, 12, 5], dtype=float)

# Функція для обчислення детермінанту матриці
def determinant(matrix):
    return np.linalg.det(matrix)

# Реалізація методу Крамера для розв'язання системи рівнянь
def solve_cramers_rule(coefficients, constants):
    n = len(coefficients)
    results = []
    main_determinant = determinant(coefficients)

    for i in range(n):
        # Заміна i-го стовпчика коефіцієнтів на вектор констант
        coeffs_copy = coefficients.copy()
        coeffs_copy[:, i] = constants

        # Обчислення детермінанту заміщеної матриці
        det_i = determinant(coeffs_copy)

        # Розв'язання за формулою Крамера
        result_i = det_i / main_determinant
        results.append(result_i)

    return results

# Розв'язання системи за допомогою Крамера
solution = solve_cramers_rule(coefficients, constants)
print("Розв'язок за допомогою формул Крамера:", solution)

Розв'язок за допомогою формул Крамера: [1.0000000000000004, 1.9999999999999982, 0.9999999999999987, -1.0]


In [26]:
# Перевірка за допомогою матричного множення
verification_a = np.dot(coefficients, solution)
print("Перевірка за допомогою матричного множення:", verification_a)

Перевірка за допомогою матричного множення: [-5. -4. 12.  5.]


In [27]:
# Перевірка за допомогою оберненої матриці
inverse_coefficients = np.linalg.inv(coefficients)
verification_b = np.dot(inverse_coefficients, constants)
print("Перевірка за допомогою оберненої матриці:", verification_b)

Перевірка за допомогою оберненої матриці: [ 1.  2.  1. -1.]


In [28]:
# Перевірка за допомогою numpy.linalg.solve()
verification_c = np.linalg.solve(coefficients, constants)
print("Перевірка за допомогою numpy.linalg.solve():", verification_c)

Перевірка за допомогою numpy.linalg.solve(): [ 1.  2.  1. -1.]


In [29]:
import numpy as np

# Задання матриць A та B
A = np.array([[7, 2, 0], [-7, -3, 2], [2, 2, 0]])
B = np.array([[0, 2, 3], [1, 0, -2], [3, 1, 0]])

# Обчислення квадратів матриць A та B
A_squared = np.square(A)
B_squared = np.square(B)

# Обчислення різниці квадратів
squared_diff = A_squared - B_squared

# Обчислення суми матриць A та B
sum_matrix = A + B

# Обчислення значення матричного виразу
result_matrix = np.dot(squared_diff, sum_matrix)
print("Результат з використанням NumPy:")
print(result_matrix)

Результат з використанням NumPy:
[[298 169 147]
 [282 165 144]
 [-53 -29 -15]]


In [30]:
import numpy as np

# Задання матриць A та B
A = np.array([[7, 2, 0], [-7, -3, 2], [2, 2, 0]])
B = np.array([[0, 2, 3], [1, 0, -2], [3, 1, 0]])

# Обчислення квадратів матриць A та B
A_squared = np.square(A)
B_squared = np.square(B)

# Обчислення різниці квадратів
squared_diff = A_squared - B_squared

# Обчислення суми матриць A та B
sum_matrix = A + B

# Обчислення значення матричного виразу за допомогою ітеративних конструкцій
result_matrix = [[0 for _ in range(len(A))] for _ in range(len(A))]

for i in range(len(A)):
    for j in range(len(A[0])):
        result_matrix[i][j] = sum((A_squared[i][k] - B_squared[i][k]) * sum_matrix[k][j] for k in range(len(A)))

print("Результат за допомогою ітеративних конструкцій:")
print(result_matrix)

Результат за допомогою ітеративних конструкцій:
[[298, 169, 147], [282, 165, 144], [-53, -29, -15]]


In [32]:
import numpy as np
import time

# Задання матриць A та B
A = np.array([[7, 2, 0], [-7, -3, 2], [2, 2, 0]])
B = np.array([[0, 2, 3], [1, 0, -2], [3, 1, 0]])

# Замір часу виконання з використанням універсальних функцій бібліотеки NumPy
start_time = time.time()

# Обчислення квадратів матриць A та B
A_squared = np.square(A)
B_squared = np.square(B)

# Обчислення різниці квадратів
squared_diff = A_squared - B_squared

# Обчислення суми матриць A та B
sum_matrix = A + B

# Обчислення значення матричного виразу
result_matrix = np.dot(squared_diff, sum_matrix)

end_time = time.time()
execution_time_numpy = end_time - start_time
print("Час виконання з використанням NumPy:", execution_time_numpy, "сек")

# Замір часу виконання за допомогою ітеративних конструкцій
start_time = time.time()

# Обчислення квадратів матриць A та B
A_squared = np.square(A)
B_squared = np.square(B)

# Обчислення різниці квадратів
squared_diff = A_squared - B_squared

# Обчислення суми матриць A та B
sum_matrix = A + B

# Обчислення значення матричного виразу за допомогою ітеративних конструкцій
result_matrix = [[0 for _ in range(len(A))] for _ in range(len(A))]

for i in range(len(A)):
    for j in range(len(A[0])):
        result_matrix[i][j] = sum((A_squared[i][k] - B_squared[i][k]) * sum_matrix[k][j] for k in range(len(A)))

end_time = time.time()
execution_time_iterative = end_time - start_time
print("Час виконання за допомогою ітеративних конструкцій:", execution_time_iterative, "сек")


Час виконання з використанням NumPy: 0.0 сек
Час виконання за допомогою ітеративних конструкцій: 0.0009989738464355469 сек
